# Generated by Django 2.1.5 on 2019-02-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='domicilio',
            new_name='direccion',
        ),
    ]
