# Generated by Django 2.1.5 on 2019-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20190211_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(null=True, to='mascota.Vacuna'),
        ),
    ]
