# Generated by Django 2.1.5 on 2019-03-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20190212_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='fecha_rescate',
            new_name='fechaRescate',
        ),
    ]
